### ISSUE TITLE
hwloc

### ISSUE THREAD

**Issue by UnixJunkie** [haesbaert/ocaml-processor#2]
maybe you can find some interesting code in there
https://www.open-mpi.org/projects/hwloc/

**Comment by haesbaert** [comment]
I did copy some stuff from mpi, basically the m1 topology thing that uses that weird os x api.
I don't plan to add much more stuff to this project but I welcome contributions, I say this because most of the topology discovery is already a bit useless. If you're in a really big machine where you want to optimize things, then you know what is what and where is where and don't really need to do any discovery at runtime. And if you're in a smallish machine then it largely doesn't matter.
